wandb_version: 1

_name_or_path:
  desc: null
  value: google/vit-base-patch16-224-in21k
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    python_version: 3.10.7
    start_time: 1679434908.444452
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 7
      - 13
      - 23
      4: 3.10.7
      5: 0.13.4
      6: 4.26.1
      8:
      - 1
      - 3
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - ViTModel
attention_probs_dropout_prob:
  desc: null
  value: 0.0
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bos_token_id:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
cross_attention_hidden_size:
  desc: null
  value: null
data_seed:
  desc: null
  value: None
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_bucket_cap_mb:
  desc: null
  value: None
ddp_find_unused_parameters:
  desc: null
  value: None
ddp_timeout:
  desc: null
  value: 1800
debug:
  desc: null
  value: '[]'
decoder_start_token_id:
  desc: null
  value: null
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
encoder_stride:
  desc: null
  value: 16
eos_token_id:
  desc: null
  value: null
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 16
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: None
evaluation_strategy:
  desc: null
  value: epoch
exponential_decay_length_penalty:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: None
full_determinism:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 4
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: true
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hidden_act:
  desc: null
  value: gelu
hidden_dropout_prob:
  desc: null
  value: 0.0
hidden_size:
  desc: null
  value: 768
hub_model_id:
  desc: null
  value: None
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': 3
    '1': 8
    '10': 17
    '11': 18
    '12': 31
    '13': 49
    '14': 16
    '15': 5
    '16': 28
    '17': 6
    '18': 30
    '19': 38
    '2': 12
    '20': 13
    '21': 7
    '22': 57
    '23': 21
    '24': 45
    '25': 25
    '26': 33
    '27': 20
    '28': 42
    '29': 37
    '3': 4
    '30': 47
    '31': 44
    '32': 23
    '33': 46
    '34': 34
    '35': 32
    '36': 19
    '37': 40
    '38': 29
    '39': 35
    '4': 0
    '40': 24
    '41': 41
    '42': 59
    '43': 15
    '44': 64
    '45': 52
    '46': 11
    '47': 10
    '48': 61
    '49': 26
    '5': 2
    '50': 27
    '51': 54
    '52': 50
    '53': 62
    '54': 55
    '55': 48
    '56': 43
    '57': 60
    '58': 51
    '59': 36
    '6': 1
    '60': 39
    '61': 56
    '62': 58
    '63': 66
    '64': 63
    '65': 53
    '7': 14
    '8': 22
    '9': 9
ignore_data_skip:
  desc: null
  value: false
image_size:
  desc: null
  value: 224
include_inputs_for_metrics:
  desc: null
  value: false
initializer_range:
  desc: null
  value: 0.02
intermediate_size:
  desc: null
  value: 3072
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
jit_mode_eval:
  desc: null
  value: false
label2id:
  desc: null
  value:
    '0': '4'
    '1': '6'
    '10': '47'
    '11': '46'
    '12': '2'
    '13': '20'
    '14': '7'
    '15': '43'
    '16': '14'
    '17': '10'
    '18': '11'
    '19': '36'
    '2': '5'
    '20': '27'
    '21': '23'
    '22': '8'
    '23': '32'
    '24': '40'
    '25': '25'
    '26': '49'
    '27': '50'
    '28': '16'
    '29': '38'
    '3': '0'
    '30': '18'
    '31': '12'
    '32': '35'
    '33': '26'
    '34': '34'
    '35': '39'
    '36': '59'
    '37': '29'
    '38': '19'
    '39': '60'
    '4': '3'
    '40': '37'
    '41': '41'
    '42': '28'
    '43': '56'
    '44': '31'
    '45': '24'
    '46': '33'
    '47': '30'
    '48': '55'
    '49': '13'
    '5': '15'
    '50': '52'
    '51': '58'
    '52': '45'
    '53': '65'
    '54': '51'
    '55': '54'
    '56': '61'
    '57': '22'
    '58': '62'
    '59': '42'
    '6': '17'
    '60': '57'
    '61': '48'
    '62': '53'
    '63': '64'
    '64': '44'
    '66': '63'
    '7': '21'
    '8': '1'
    '9': '9'
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_eps:
  desc: null
  value: 1.0e-12
learning_rate:
  desc: null
  value: 5.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: true
local_rank:
  desc: null
  value: -1
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: passive
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: models/model_Hull Type\runs\Mar21_22-41-51_DESKTOP-78HEDU9
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 10
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: f1
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: vit
mp_parameters:
  desc: null
  value: ''
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_attention_heads:
  desc: null
  value: 12
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_channels:
  desc: null
  value: 3
num_hidden_layers:
  desc: null
  value: 12
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 15
optim:
  desc: null
  value: adamw_hf
optim_args:
  desc: null
  value: None
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: models/model_Hull Type
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
patch_size:
  desc: null
  value: 16
per_device_eval_batch_size:
  desc: null
  value: 16
per_device_train_batch_size:
  desc: null
  value: 16
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
qkv_bias:
  desc: null
  value: true
ray_scope:
  desc: null
  value: last
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''wandb'']'
resume_from_checkpoint:
  desc: null
  value: None
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: models/model_Hull Type
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: epoch
save_total_limit:
  desc: null
  value: None
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: true
suppress_tokens:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: None
tf_legacy_loss:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: None
torch_compile_mode:
  desc: null
  value: None
torch_dtype:
  desc: null
  value: null
torchdynamo:
  desc: null
  value: None
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 16
transformers_version:
  desc: null
  value: 4.26.1
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
warmup_ratio:
  desc: null
  value: 0.1
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
xpu_backend:
  desc: null
  value: None
