wandb_version: 1

_name_or_path:
  desc: null
  value: google/vit-base-patch16-224
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    - 1: eval/loss
      5: 1
      6:
      - 1
    - 1: eval/accuracy
      5: 1
      6:
      - 1
    - 1: eval/f1
      5: 1
      6:
      - 1
    - 1: eval/precision
      5: 1
      6:
      - 1
    - 1: eval/recall
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
    python_version: 3.10.7
    start_time: 1679569705.338813
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 7
      - 13
      - 23
      4: 3.10.7
      5: 0.13.4
      6: 4.26.1
      8:
      - 1
      - 3
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - ViTForImageClassification
attention_probs_dropout_prob:
  desc: null
  value: 0.0
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bos_token_id:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
cross_attention_hidden_size:
  desc: null
  value: null
data_seed:
  desc: null
  value: None
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_bucket_cap_mb:
  desc: null
  value: None
ddp_find_unused_parameters:
  desc: null
  value: None
ddp_timeout:
  desc: null
  value: 1800
debug:
  desc: null
  value: '[]'
decoder_start_token_id:
  desc: null
  value: null
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
encoder_stride:
  desc: null
  value: 16
eos_token_id:
  desc: null
  value: null
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 16
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: None
evaluation_strategy:
  desc: null
  value: epoch
exponential_decay_length_penalty:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: None
full_determinism:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 4
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: true
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hidden_act:
  desc: null
  value: gelu
hidden_dropout_prob:
  desc: null
  value: 0.0
hidden_size:
  desc: null
  value: 768
hub_model_id:
  desc: null
  value: None
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
    '10': LABEL_10
    '11': LABEL_11
    '12': LABEL_12
    '13': LABEL_13
    '14': LABEL_14
    '15': LABEL_15
    '16': LABEL_16
    '17': LABEL_17
    '18': LABEL_18
    '19': LABEL_19
    '2': LABEL_2
    '20': LABEL_20
    '21': LABEL_21
    '22': LABEL_22
    '23': LABEL_23
    '24': LABEL_24
    '25': LABEL_25
    '26': LABEL_26
    '27': LABEL_27
    '28': LABEL_28
    '29': LABEL_29
    '3': LABEL_3
    '30': LABEL_30
    '31': LABEL_31
    '32': LABEL_32
    '33': LABEL_33
    '34': LABEL_34
    '35': LABEL_35
    '36': LABEL_36
    '37': LABEL_37
    '38': LABEL_38
    '39': LABEL_39
    '4': LABEL_4
    '40': LABEL_40
    '41': LABEL_41
    '42': LABEL_42
    '43': LABEL_43
    '44': LABEL_44
    '45': LABEL_45
    '46': LABEL_46
    '47': LABEL_47
    '48': LABEL_48
    '49': LABEL_49
    '5': LABEL_5
    '50': LABEL_50
    '51': LABEL_51
    '52': LABEL_52
    '53': LABEL_53
    '54': LABEL_54
    '55': LABEL_55
    '56': LABEL_56
    '57': LABEL_57
    '58': LABEL_58
    '59': LABEL_59
    '6': LABEL_6
    '60': LABEL_60
    '61': LABEL_61
    '62': LABEL_62
    '63': LABEL_63
    '64': LABEL_64
    '65': LABEL_65
    '66': LABEL_66
    '7': LABEL_7
    '8': LABEL_8
    '9': LABEL_9
ignore_data_skip:
  desc: null
  value: false
image_size:
  desc: null
  value: 224
include_inputs_for_metrics:
  desc: null
  value: false
initializer_range:
  desc: null
  value: 0.02
intermediate_size:
  desc: null
  value: 3072
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
jit_mode_eval:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
    LABEL_10: 10
    LABEL_11: 11
    LABEL_12: 12
    LABEL_13: 13
    LABEL_14: 14
    LABEL_15: 15
    LABEL_16: 16
    LABEL_17: 17
    LABEL_18: 18
    LABEL_19: 19
    LABEL_2: 2
    LABEL_20: 20
    LABEL_21: 21
    LABEL_22: 22
    LABEL_23: 23
    LABEL_24: 24
    LABEL_25: 25
    LABEL_26: 26
    LABEL_27: 27
    LABEL_28: 28
    LABEL_29: 29
    LABEL_3: 3
    LABEL_30: 30
    LABEL_31: 31
    LABEL_32: 32
    LABEL_33: 33
    LABEL_34: 34
    LABEL_35: 35
    LABEL_36: 36
    LABEL_37: 37
    LABEL_38: 38
    LABEL_39: 39
    LABEL_4: 4
    LABEL_40: 40
    LABEL_41: 41
    LABEL_42: 42
    LABEL_43: 43
    LABEL_44: 44
    LABEL_45: 45
    LABEL_46: 46
    LABEL_47: 47
    LABEL_48: 48
    LABEL_49: 49
    LABEL_5: 5
    LABEL_50: 50
    LABEL_51: 51
    LABEL_52: 52
    LABEL_53: 53
    LABEL_54: 54
    LABEL_55: 55
    LABEL_56: 56
    LABEL_57: 57
    LABEL_58: 58
    LABEL_59: 59
    LABEL_6: 6
    LABEL_60: 60
    LABEL_61: 61
    LABEL_62: 62
    LABEL_63: 63
    LABEL_64: 64
    LABEL_65: 65
    LABEL_66: 66
    LABEL_7: 7
    LABEL_8: 8
    LABEL_9: 9
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_eps:
  desc: null
  value: 1.0e-12
learning_rate:
  desc: null
  value: 5.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: true
local_rank:
  desc: null
  value: -1
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: passive
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: models/ViT_Hull Type\runs\Mar23_12-08-59_DESKTOP-78HEDU9
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 10
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: f1
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: vit
mp_parameters:
  desc: null
  value: ''
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_attention_heads:
  desc: null
  value: 12
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_channels:
  desc: null
  value: 3
num_hidden_layers:
  desc: null
  value: 12
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 15
optim:
  desc: null
  value: adamw_hf
optim_args:
  desc: null
  value: None
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: models/ViT_Hull Type
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
patch_size:
  desc: null
  value: 16
per_device_eval_batch_size:
  desc: null
  value: 16
per_device_train_batch_size:
  desc: null
  value: 16
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
qkv_bias:
  desc: null
  value: true
ray_scope:
  desc: null
  value: last
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''wandb'']'
resume_from_checkpoint:
  desc: null
  value: None
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: models/ViT_Hull Type
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: epoch
save_total_limit:
  desc: null
  value: None
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: true
suppress_tokens:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: None
tf_legacy_loss:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: None
torch_compile_mode:
  desc: null
  value: None
torch_dtype:
  desc: null
  value: null
torchdynamo:
  desc: null
  value: None
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 16
transformers_version:
  desc: null
  value: 4.26.1
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
warmup_ratio:
  desc: null
  value: 0.1
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
xpu_backend:
  desc: null
  value: None
